### ISSUE TITLE
can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by littlepea** [jazzband/django-constance#49] opened 2013-12-09 06:27 UTC
@jezdez 

If trying to save a datetime type setting getting this in Django 1.5.4:

```
TypeError
Exception Value:    
can't compare offset-naive and offset-aware datetimes
Exception Location: constance/admin.py in changelist_view, line 119
```
- http://stackoverflow.com/questions/7065164/how-to-make-an-unaware-datetime-timezone-aware-in-python
- http://stackoverflow.com/questions/796008/cant-subtract-offset-naive-and-offset-aware-datetimes

**Comment by rvernica** [comment] 2016-12-26 21:05
I can reproduce this as follows.
`settings.py`:
```
USE_TZ = True
CONSTANCE_CONFIG = {
    'taz': (datetime.datetime(1972, 11, 30, 1, 10, 0), 'help text'),
}
```
Go to Constance in Django Admin and just hit Save. You get:
```
TypeError at /admin/constance/config/

can't compare offset-naive and offset-aware datetimes

Request Method: 	POST
Request URL: 	http://localhost:8000/admin/constance/config/
Django Version: 	1.10.4
...

admin.py in save
137. if getattr(config, name) != self.cleaned_data[name]:
▼ Local vars
Variable 	Value
name 	'taz'
self 	<ConstanceForm bound=True, valid=True, fields=(version;taz)>
```
If I set `USE_TZ = False` it works fine. (BTW, `USE_TZ = True` is the default in Django).

---
Now, if I use `make_aware` when I define the default, it works even with `USE_TZ = True`:
```
CONSTANCE_CONFIG = {
    'taz2': (timezone.make_aware(
        datetime.datetime(1972, 11, 30, 1, 10, 0)), 'help text'),
}
```
(I had to rename the variable since I can't delete or reset the old one.)

### System configuration

* Constance revision: 8db90e808756f62941c025c6dc522156d7271db0
* Django version: `1.10.4`
* Python version: `2.7.12`

**Comment by camilonova** [comment] 2017-01-11 16:46
@rvernica you need to use:

```
from pytz import timezone

CONSTANCE_CONFIG = {
    'taz2': (timezone(TIME_ZONE).localize(datetime(1972, 11, 30, 1, 10, 0)), 'help text'),
}            
```

in your settings file

**Comment by rvernica** [comment] 2017-01-18 22:35
@jezdez, care to reopen this?

**Comment by jezdez** [comment] 2017-01-19 07:58
@rvernica done

**Comment by madEng84** [comment] 2017-06-20 16:19
Is this bug resolved?
Thanks

**Comment by camilonova** [comment] 2018-07-21 15:37
@rvernica can you please check if this was already fixed?

**Comment by zodman** [comment] 2018-11-01 17:57
i reproduce with django 1.10

**Comment by zodman** [comment] 2018-11-02 02:14
i had reproduce the error PR #311

**Comment by zodman** [comment] 2018-11-02 07:03
fix on the PR #311

**Comment by dtatarkin** [comment] 2019-08-08 08:34
@jezdez, care to reopen this?

**Comment by jezdez** [comment] 2019-08-08 11:04
Sure!

**Comment by zodman** [comment] 2019-08-08 18:35
i suggest this bug close because 

You mixing the datetimes with timezone and without timezone. That the reason django fired the exception.

The correct way:

if you use USE_TZ = True the config CONSTANCE_CONFIG should contains datetimes with timezone
If use USE_TZ= False the CONSTANCE_CONFIG should use datetime native.

I had working for a week on this PR but... at the end i get that conclusion. it not be resolved with a code change, only with a documentation change.

**Comment by dtatarkin** [comment] 2019-08-08 20:13
Yes, that makes sense. We can just warn a user when naive datetime is used along with `USE_TZ = True`.  On the other hand, if there are a lot of naive datetime values already stored in the database, https://github.com/jazzband/django-constance/pull/337 will deal with that. Moreover, there was another try to deal with naive datetime  values when `USE_TZ = True` https://github.com/jazzband/django-constance/issues/169.
I think auto-convert naive datetime to datetime with timezone is more user-friendly than return HTTP 500.

**Closed** 2019-08-12 15:58 UTC
