### ISSUE TITLE
"Reset to default" option isn't looking good

### ISSUE THREAD

**Issue by auuron** [jazzband/django-constance#188] opened 2016-12-29 14:38 UTC
![image](https://cloud.githubusercontent.com/assets/1974216/21546070/ac93e9b6-cddc-11e6-8bca-8d7c84212393.png)

### System configuration

* Django version: 1.9.12
* Python version: 2.7.12
* django-grapelli: 2.8.3

**Comment by rvernica** [comment] 2017-01-10 18:49
I tried to reproduce this using *django-grappelli* `2.9.1` and the *Reset to default* link does not even appear.

The template displaying the link looks like this:
```html
        <td>
            {{ item.form_field.errors }}
            {{ item.form_field }}
            <br>
            <a href="#" onClick="document.getElementById('{{ item.form_field.auto_id }}').value = '{{ item.default|escapejs }}'; return false;">Reset to default</a>
        </td>
```
So, my best guess is that *django-grappelli* only picks up the `item.form_field.errors` and `item.form_field` content and skips the rest of the HTML somehow.

**Comment by jezdez** [comment] 2017-11-26 00:10
Apologies, but we've had various tickets about Grappelli support over the years and I'm afraid I'll have to close this again as a thing that needs to be fixed there, not here.

**Closed by jezdez** 2017-11-26 00:10 UTC
