### ISSUE TITLE
Caching getting multiple values

### ISSUE THREAD

**Issue by aboueleyes** [jazzband/django-constance#527] opened 2023-08-15 09:31 UTC
### Describe the problem

Currently, you cannot `mget` in Database Backend does not use cache at all. is there are reason for this?
In my case, I have a view that needs multiple values, and I need to utilize the cache.

**Comment by Mogost** [comment] 2024-09-10 17:24
Isn't this a duplicate of https://github.com/jazzband/django-constance/issues/344 ?

**Comment by camilonova** [comment] 2024-09-11 13:45
It is a duplicate. I'm closing this.

**Closed by camilonova** 2024-09-11 13:45 UTC
